version: '3.8'
services:
  nginx-proxy:
    image: nginx:alpine  
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/auth/.htpasswd:/etc/nginx/auth/.htpasswd:ro
    networks:
      - app-network
    restart: always
    cap_add:
      - NET_ADMIN
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=mydatabase
      - PROXY_HOST=nginx-proxy
      - PROXY_PORT=80
      - PROXY_USERNAME=your_username
      - PROXY_PASSWORD=your_password
    networks:
      - app-network
    depends_on:
      - nginx-proxy
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge